image: Ubuntu1804

platform:
    - x64

install:
    - nvm use v15
    - npm ci --only=production

build_script:
    - echo "nothing to build"

# defined specific build configs for different branches
for:
-
    branches:
        only:
            - master
    deploy_script:
        - npm run publish-production
-
    branches:
        only:
            - develop
    install:
        - nvm use v11
        - npm install
        - git clone https://github.com/strawbees/code-ui.git
        - cd code-ui
        - git checkout develop
        - npm link
        - cd ..
        - npm link @strawbees/code-ui
    build_script:
        - npm run build-develop
    deploy_script:
        - npm run publish-develop
-
    branches:
        only:
            - /feature*/
    environment:
        S3_BUCKET: strawbees-test
    deploy_script:
        - npm run publish-stage

# This will build based on `CONFIG` environment variable

version: "{build}"

skip_tags: true

branches:
    only:
        - master
        - develop
        - /feature*/
